### PR TITLE
Better credits formatting

### PR DESCRIPTION
**Pull request by kauegimenes**

### CODE REVIEW

**Comment by Giszmo** [comment]
Hesitant as the associations you put there might be controversial but as your changes I guess I can accept it, assuming these are the conclusions you drew from publicly available sources. If only you could set the branch "develop" as target, not "master" please.

**Comment by jonathancross** [comment]
@kauegimenes Still waiting on you to change the branch to "develop".

**Comment by Ssbodyshop** [comment]
Can some one help me need to transfer coins. To wallets will pay

**Comment by kauegimenes** [comment]
@Giszmo @jonathancross sorry for the delay

**Comment by Ssbodyshop** [comment]
Hey I sent u a wallet did u get it

James shank

On Feb 8, 2018 10:00 AM, "Kauê Gimenes" <notifications@github.com> wrote:

@Giszmo <https://github.com/giszmo> @jonathancross
<https://github.com/jonathancross> sorry for the delay

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/mycelium-com/wallet-android/pull/386#issuecomment-364157079>,
or mute the thread

**Pull request merged**
