### PR TITLE
Improved English

### PR DESCRIPTION
**Pull request by blrhc**
flows better

### CODE REVIEW

**Comment by Hitgub01** [comment]
The person who can solve my problem with crypto de suisse get's an reward of 250 euro.

**Comment by Hitgub01** [comment]
It means i can login to crypto de suisse but i don't know how to transfer it to Bitstamp..., i've been contacted some one named Nathan Tendler he told me he was a broker... he took some actions but i couldn't follow it

**Comment by blotterandbars** [comment]
How do I get into my account it says wrong password and idk passphrase

**Comment by blotterandbars** [comment]
I've made new account and already made a claim ticket but how long are we waiting lol

**Comment by Hitgub01** [comment]
The problem is solved by ofwel.

**Comment by Hitgub01** [comment]
Itself 😉

**Comment by Giszmo** [comment]
Sorry for closing this but it's very low effort and open since 2 years. Don't want to bother colleagues with it.

**Pull request closed without merging**
