### PR TITLE
Add hebrew localizations

### PR DESCRIPTION
**Pull request by yanivmad**
Hebrew localizations

### CODE REVIEW

**Comment by sagivo** [comment]
LGTM

**Comment by yanivmad** [comment]
What is LGTM??
and why isn't it merged yet?

**Comment by sagivo** [comment]
http://lmgtfy.com/?q=LGTM

**Comment by sergeylappo** [comment]
@yanivmad, sorry for such a long wait, we had hard time.
We do use crowdin for translation. Please send me your email: sergey.lappo@mycelium.com I'll send you invite.

**Pull request closed without merging**
