### PR TITLE
Corrections

### PR DESCRIPTION
**Pull request by PaulRomerolegal**
spelling + capitalization

### CODE REVIEW

**Comment by Giszmo** [comment]
Thank you. Looks good. Could you please point the PR towards the develop branch?

**Comment by jonathancross** [comment]
@PaulRomerolegal Still waiting on you to change the branch to "develop".

**Comment by jonathancross** [comment]
Hello @PaulRomerolegal - this will probably be closed if you don't respond.

**Comment by Giszmo** [comment]
obsolete. other pr merged.

**Pull request closed without merging**
